//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Fair_Sys_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanyRequiredSkills = new HashSet<CompanyRequiredSkill>();
            this.EventFeedbacks = new HashSet<EventFeedback>();
            this.StudentSelectedCompanies = new HashSet<StudentSelectedCompany>();
            this.StudentsFeedbacks = new HashSet<StudentsFeedback>();
            this.InterviewSchedules = new HashSet<InterviewSchedule>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> NoOfInterviewers { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public Nullable<int> TimeSlot { get; set; }
        public string Profile { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
        public int rate { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual Company Company2 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CompanyRequiredSkill> CompanyRequiredSkills { get; set; }
        public virtual ICollection<EventFeedback> EventFeedbacks { get; set; }
        public virtual ICollection<StudentSelectedCompany> StudentSelectedCompanies { get; set; }
        public virtual ICollection<StudentsFeedback> StudentsFeedbacks { get; set; }
        public virtual ICollection<InterviewSchedule> InterviewSchedules { get; set; }
    }
}
