//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Fair_Sys_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobFairMgtEntities : DbContext
    {
        public JobFairMgtEntities()
            : base("name=JobFairMgtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Company> Companies { get; set; }
        public DbSet<EventFeedback> EventFeedbacks { get; set; }
        public DbSet<FeedBack> FeedBacks { get; set; }
        public DbSet<InterviewSchedule> InterviewSchedules { get; set; }
        public DbSet<Skill> Skills { get; set; }
        public DbSet<SocietyMember> SocietyMembers { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentsFeedback> StudentsFeedbacks { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<CompanyRequiredSkill> CompanyRequiredSkills { get; set; }
        public DbSet<StudentSelectedCompany> StudentSelectedCompanies { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<StudentSkill> StudentSkills { get; set; }
    }
}
