//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Fair_Sys_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public FeedBack()
        {
            this.StudentsFeedbacks = new HashSet<StudentsFeedback>();
        }
    
        public int Id { get; set; }
        public string FeedBack1 { get; set; }
    
        public virtual ICollection<StudentsFeedback> StudentsFeedbacks { get; set; }
    }
}
